/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <gsthelloImplFactory.hpp>
#include "gsthelloImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_gsthello_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentogsthelloImpl"

namespace kurento
{
namespace module
{
namespace gsthello
{

gsthelloImpl::gsthelloImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline)
: FilterImpl (config, std::dynamic_pointer_cast<MediaObjectImpl> (mediaPipeline))
{
  // FIXME: Implement this
}

MediaObjectImpl *
gsthelloImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new gsthelloImpl (config, mediaPipeline);
}

gsthelloImpl::StaticConstructor gsthelloImpl::staticConstructor;

gsthelloImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* gsthello */
} /* module */
} /* kurento */
