/* Autogenerated with kurento-module-creator */

#ifndef __GSTHELLO_IMPL_HPP__
#define __GSTHELLO_IMPL_HPP__

#include "FilterImpl.hpp"
#include "gsthello.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace gsthello
{
class gsthelloImpl;
} /* gsthello */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::gsthello::gsthelloImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace gsthello
{

class gsthelloImpl : public FilterImpl, public virtual gsthello
{

public:

  gsthelloImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~gsthelloImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* gsthello */
} /* module */
} /* kurento */

#endif /*  __GSTHELLO_IMPL_HPP__ */
